// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ms_main
std::string ms_main(NumericVector nsam, NumericVector nreps, NumericVector t, NumericVector variable_list_rcpp, IntegerVector I_rcpp, NumericVector migr_rcpp, NumericVector migration, NumericMatrix en, NumericMatrix ej, NumericVector seeds);
RcppExport SEXP _msPac_ms_main(SEXP nsamSEXP, SEXP nrepsSEXP, SEXP tSEXP, SEXP variable_list_rcppSEXP, SEXP I_rcppSEXP, SEXP migr_rcppSEXP, SEXP migrationSEXP, SEXP enSEXP, SEXP ejSEXP, SEXP seedsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type nsam(nsamSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nreps(nrepsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type variable_list_rcpp(variable_list_rcppSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type I_rcpp(I_rcppSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type migr_rcpp(migr_rcppSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type migration(migrationSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type en(enSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ej(ejSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seeds(seedsSEXP);
    rcpp_result_gen = Rcpp::wrap(ms_main(nsam, nreps, t, variable_list_rcpp, I_rcpp, migr_rcpp, migration, en, ej, seeds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_msPac_ms_main", (DL_FUNC) &_msPac_ms_main, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_msPac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
