# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ms_main <- function(nsam, nreps, t, I_rcpp, migr_rcpp, migration, en, ej, es) {
    .Call(`_msPac_ms_main`, nsam, nreps, t, I_rcpp, migr_rcpp, migration, en, ej, es)
}

